### ISSUE TITLE
Voting for the Mensa dishes

### ISSUE THREAD

**Issue by Kaazyra** [neuland-ingolstadt/neuland.app#102]
The User can vote with e.g 5 stars or up and down vote for the different dishes. 
The other User can see the rating.

**Comment by M4GNV5** [comment]
The Werkswelt-App seems to be a simple webview of https://stwer.my-mensa.de/index.php?v=5452592&os=ios&hyp=1 (on iOS). I do not see any voting functionality?

**Comment by Curryking31** [comment]
![image](https://user-images.githubusercontent.com/43369463/139927334-a6fdd575-11f5-4266-bfdd-14c7d28250d6.png)

You can see it by clicking on a menu you want to rate.

**Comment by M4GNV5** [comment]
When clicking one of the stars a GET request to the following URL is made:
```
https://stwer.my-mensa.de/rating/votes/update2/<redacted>/52Ur9/iH9/B9/979cc36be4337204d95f620f58373637/5/1635894000?_=1635937391137
```

The URL is built in javascript using:
```js
/rating/votes/update2/'+idk+'/'+aid+'/'+pid+'/'+lid+'/'+md5+'/'+vote+'/'+timestamp
```

where `idk` is a user identifier which is loaded from localstorage, `aid`, `pid`, `lid` and `md5` are meal identifiers which are included in the pages HTML code. `vote` is a number from 1-5 (how many stars) and `timestamp` is the current timestamp (probably to prevent caching)

**Comment by Robert27** [comment]
Since we now assign an unique ID to each meal (#378), we could easily implement this. We just need to build some backend database to store the ratings. 
Additionally I suggest to add another button "not available" to report unavailable meals.

**Comment by BuildmodeOne** [comment]
> Since we now assign an unique ID to each meal (#378), we could easily implement this. We just need to build some backend database to store the ratings. Additionally I suggest to add another button "not available" to report unavailable meals.

Sadly, we still have pseudo-unique IDs just with the day and start of the title hash. 

This is due to the fact that we cannot ensure that every meal is 100% identical to others, as the titles often change. 

We should revise the ID system for the voting system so that we can ensure that it does not match another meal. 

Since pseudo-unique IDs were sufficient for the current setup (SSR/ISR and sharing), these are still "error-prone"

**Comment by Robert27** [comment]
Thank you for your insightful comment. I discussed this with @alexhorn earlier today. However, we now have high doubts that there are enough users who subsequently evaluate the food. Also they probably tend to extreme values, for example, rate the food because only it was bad, otherwise forget it.

In addition, we would have to ensure that our results cannot be manipulated and can only be sent once. For this we could either use the Azure Authentication or App Attest Service, but everything a little overkill...

**Comment by BuildmodeOne** [comment]
> Thank you for your insightful comment. I discussed this with @alexhorn earlier today. However, we now have high doubts that there are enough users who subsequently evaluate the food. Also they probably tend to extreme values, for example, rate the food because only it was bad, otherwise forget it. In addition, we would have to ensure that our results cannot be manipulated and can only be sent once. For this we could either use the Azure Authentication or App Attest Service, but everything a little overkill...

I completely agree with you, the problems we have with it and the overkill solutions we would need for it do not have a good cost/benefit ratio. Should we therefore close the issue?
