### ISSUE TITLE
Show time until free occupancy in room map

### ISSUE THREAD

**Issue by BuildmodeOne** [neuland-ingolstadt/neuland.app#142]
As with the overview for free rooms, which shows how long they are still free, it would be practical if a time were given for occupied rooms when they will be available again.

![image](https://user-images.githubusercontent.com/39560569/165061216-cd808631-22fe-48aa-a0fe-df05ac7dc9df.png)

**Comment by Robert27** [comment]
Thanks for your valuable feature request.
We should consider displaying the time until the room is occupied again ("frei von 11 Uhr **bis 14:30 Uhr**").
Or even more useful, display the remaining time in minutes / hours, if that is possible in real time ("frei von 11 Uhr **für 3,5h**").
Due to the gray background color, I think there should be no confusion with actual free rooms.
