### ISSUE TITLE
Theme suggestion: Pride theme

### ISSUE THREAD

**Issue by BuildmodeOne** [neuland-ingolstadt/neuland.app#144]
for pride month pls 🏳️‍🌈

**Comment by alexhorn** [comment]
@chiaragambirasio @Kaazyra @sarah-kath
Do you have any suggestions on how to design this?

**Comment by Supernova1750** [comment]
Ideas:
- Prideflag buttons
- logo on the lop left can be in rainbow colors
- the individual logos could also be rainbow colored

We could use [SVG masking](https://getflywheel.com/layout/css-svg-clipping-and-masking-techniques/) for the icons, unless there are better methods. Also that example doesnt really work as shown, at least i couln't get it to work.

**Comment by alexhorn** [comment]
@WebFreak001 suggested this CSS based solution for adding a rainbow background to the logo:

```
background: linear-gradient(180deg, red 16.66%, orange 16.67%, orange 33.33%, yellow 33.34%, yellow 49.99%, green 50%, green 66.66%, blue 66.67%, blue 83.33%, purple 83.34%);
font-weight: bold;
color: white;
text-shadow: 0 0 2px black;
```

**Comment by Supernova1750** [comment]
I would suggest rotating the rainbow patter or else it would look a little boring, especially for the buttons as the pattern would look either very stretched out or would not display all colors.

**Comment by alexhorn** [comment]
Added prototype suggested by @WebFreak001 in fbded4d6de3eab60eec08f36e5ae0e8142d3f150.

**Comment by Robert27** [comment]
I suggest the following design. The Pride flag has been adjusted in its colors. In addition, a black background design is used here for the first time, which gives it a unique feature.

The problem with the unreadable text was solved by a dark blue color, because here the contrast to yellow and green is best, also a glowing effect was added.
![image](https://user-images.githubusercontent.com/53063597/171509073-9a646836-15b4-4df7-af69-faa7817ca860.png)

**Comment by Robert27** [comment]
I uploaded the design with the high contrast darkmode.
What we still might add are animations, like confetti when you hover / click the navbar, like Google does in search. Or a pride flag as color for an active tab in the tabbar in mobile view.
