### ISSUE TITLE
Text overflow in Retro Theme at Food View

### ISSUE THREAD

**Issue by Robert27** [neuland-ingolstadt/neuland.app#180]
PR #178 has fixed the problem for the mobility card, however the problem still exists for the food view.
 
![D7CDCE3B-E1FD-4A91-BF63-9AF1E7CAC3CE](https://user-images.githubusercontent.com/53063597/216780287-469db27b-58c8-422a-b5a8-49033539761f.png)

Also, in my opinion, the font size is way too big.

**Comment by Habinator** [comment]
This issue is partially outdated.
There is no overflow in the foodview any more since the price got moved to a new horizontal row.
However, LukasVoreck & me noticed that the overflow happens with the "Stundenplan" view as well.

Additionally, we tried making the body font smaller since it is so huge but have not yet found a fix which works on all browsers. (size-adjust is not supported in Safari)
