### ISSUE TITLE
Redesign profile tab

### ISSUE THREAD

**Issue by Kaazyra** [neuland-ingolstadt/neuland.app#182]
Redesign the profile tab like this:
Add linkouts to Moodle, Primuss and email
Add theme changer
Add food settings: intolerances, vegan/vegetarian filter (currently on the Mensa page)

![Profil 1 0](https://user-images.githubusercontent.com/82609263/219126945-3e8483ee-0061-4a21-8887-0b352887e843.png)

**Comment by FabianSimonGross** [comment]
Since we do not have a profile picture nor the data if someone is going to the next Semester I'll go and leave these Features out until we might get them. But I'm not being honest if I say we will get them, cause we don't.

Current State would look like this:
![grafik](https://user-images.githubusercontent.com/81598210/220967169-461c91c0-7f71-4e4a-9784-ae69ef700cb1.png)

**Comment by FabianSimonGross** [comment]
So since we do not have either a profile picture or the information if someone is going to the next term, I'm going to leave specifically those two features out. And the Edit "Profile" will be diverged to a show all "Informations" since we do not offer an own account (Privacy Policy doesn't allow for that)

As well as I'm not going to diverge from the Base-Design of the App.

I worked on a state that would look similar to the following picture:
![grafik](https://user-images.githubusercontent.com/81598210/220967889-557d2b86-38f2-4f9e-b22d-ea5b326d6737.png)

**Comment by Robert27** [comment]
Looks good to me.
Personally, I wouldn't rule out the new design entirely. Let’s open a new issue and plan the design redesign there, since this was also designed by UX team.

Regarding the profile photo, we could simply display both initialys with colored background.

**Comment by Kaazyra** [comment]
Hey @FabianSimonGross 
Looks good, I only have 2 comments on the design:
Can you remove the border and make the background slightly gray instead.
Can't you make the line in the middle all the way to the edge? (Like in the Example Design )

Reason: what it looks like now looks very "old" and that would adapt it to the modern design.

**Comment by FabianSimonGross** [comment]
> Looks good to me. Personally, I wouldn't rule out the new design entirely. Let’s open a new issue / milestone and plan the design redesign there, since this was also designed by the UX team.
> 
> Regarding the profile photo, we could simply display both initialys with colored background.

@Kaazyra, I'd recommend using a milestone with the new design and the new issue. Because I guess the design should be implemented through out the whole app. This is a little more massive undertaking because we use Bootstrap 4? and should neither way update to Bootstrap 5 in this process we could implement the new design.
