### ISSUE TITLE
Change Mensa tab

### ISSUE THREAD

**Issue by Kaazyra** [neuland-ingolstadt/neuland.app#183]
Add days of the week 
Add icon for vegan and vegetarian food 

![Mensa 1 0](https://user-images.githubusercontent.com/82609263/219128322-961eeedd-b5b8-4c06-9951-342f407915df.png)

**Comment by M4GNV5** [comment]
I do not think the Mensa provides images of the food? We could freestyle the images using dall-e/stablediffusion though :laughing:

**Comment by FabianSimonGross** [comment]
@M4GNV5 as nice as dall-e/stablediffusion is, we should not implant wrong images of the food into peoples brains, this would harm our own App as well as the reputation of Mensa/Reimanns. Stick to what we have is the best Option here.

We do not have either pictures of the food nor a "Like It"-Button

The person implementing this should take following advice:
Move the Names all the way to the left, remove the Like Button and maybe vertically center the price.

Otherwise I would also stick to the Base-Design of the App (this is very "Appley" and doesn't fit all the way our theming)
For reference with what is meant by Base-Design look at the following issue: #182

**Comment by Kaazyra** [comment]
@FabianSimonGross 
I think you're right about the pictures

I replied to the other post because of the design

**Comment by FabianSimonGross** [comment]
I've implemented this so far in the old design. 

As referenced in the another issue (#182), whe should open a new issue which describes the new design through out the whole app. Best with mock-ups, and there of course in the first step keep open to whatever you think, but afterwards maybe identify what is possible by what data we get provided.

**Comment by Robert27** [comment]
@Kaazyra 
I'm currently developing the React Native version of the neuland.app. This brings up a few questions for me.
What alternatives do you foresee for the photos? Should we show only the flags or also the allergens under the title? How should we visually separate the different restaurants, with a heading?

Also, in my research, I came across the design of the Dresden [canteen app](https://apps.apple.com/app/id1481891701). They only show today and tomorrow in the picker and the rest of the days in the menu. Also, the flags are displayed as emoji / banners. 
What do you think about this implementation? In my opinion this would be a good compromise to avoid the big SwipeableTabs element with the days and still show all available days.


<img src="https://github.com/neuland-ingolstadt/neuland.app/assets/53063597/1cb4cf8b-d0d3-4266-8e46-77891ab9404b" width=250>
<img src="https://github.com/neuland-ingolstadt/neuland.app/assets/53063597/bab0b09d-6b36-4082-90f0-25f702befa65" width=250>

**Comment by Robert27** [comment]
closed by #315 #309 #312 etc.
