### ISSUE TITLE
Event calendar export to private calendar

### ISSUE THREAD

**Issue by Schrottpage** [neuland-ingolstadt/neuland.app#205]
As a student of THI I would like to be able to export events (of student clubs etc.) to my private calendar, comparable to the export for the exam dates.

**Comment by alexhorn** [comment]
You can subscribe to the iCal API using Google / Apple Calendar: https://neuland.app/api/cl-events.ics

**Comment by FabianSimonGross** [comment]
@alexhorn isn't it possible to put this in a button? Like Subscribe to Events.

**Comment by Robert27** [comment]
The API link does not work on iOS/MacOS because the validation of the [RFC 5545](https://www.rfc-editor.org/rfc/rfc5545) specification fails.

![image](https://user-images.githubusercontent.com/53063597/224514271-cca4bc85-42d2-4781-9884-5a6bc263f0f3.png)

**Comment by FabianSimonGross** [comment]
Yeah my thinking is actually we should improve on the timetable function, so that this button gets unnecessary.

eg. Important Days should have a Information on top of the timetable that reminds someone about examination phases, free days and of course put the club events the user is interested so that they are diffrent from normal lectures but you can see if they fit your timetable.

Maybe we make this add to native calendar a hidden feature?

With the capacitor app, we could talk about togglable push informations like "Next lecture in 5 Minutes... D101"

**Comment by alexhorn** [comment]
Oops, I had the URL wrong. This is the one: https://neuland.app/api/cl-events?format=ical

**Comment by Robert27** [comment]
Discussed at the hackathon. We will instead display the events in the Neuland Next calendar, but exporting would endanger the daily number of users.
