### ISSUE TITLE
Non-Veggie Meals are labeled as Veggie

### ISSUE THREAD

**Issue by Curryking31** [neuland-ingolstadt/neuland.app#234]
When you have a look at the Meal-Tab you see, that a non-veggie-meal is labeled as veggie. I am not sure if this is because of wrong data from the API or a bug.
![image](https://user-images.githubusercontent.com/43369463/229476750-9f7ebe03-6497-407e-b751-fd80ea62c1c3.png)

**Comment by Robert27** [comment]
Thanks for your issue, it is an API error.
There is little we can do here, but we already protect ourselves with the "information without guarantee" note in the detail view.
Here is a screenshot of the official Mensa page / API:<img width="639" alt="Screenshot 2023-04-03 at 12 10 07" src="https://user-images.githubusercontent.com/53063597/229480003-b5b6b536-6c30-4998-af4b-bda67c7a822f.png">

**Comment by BuildmodeOne** [comment]
We could add a few additional checks, which already check such errors. Simultaneous flags like 'Poultry' and 'Vegetarian' should obviously be marked as errors.

**Comment by Robert27** [comment]
Yes that might be a good idea, however I am unsure regarding how we may / should change the official data.

**Comment by BuildmodeOne** [comment]
Instead of showing the green thumbs up we could show the usual warning or just an information in yellow 

![image](https://user-images.githubusercontent.com/39560569/229509614-304d3014-264b-41e2-a525-bb6d0624c338.png)

![image](https://user-images.githubusercontent.com/39560569/229509701-86678392-2b22-4b49-92e1-3fd35d84e2c7.png)

**Comment by M4GNV5** [comment]
The reason this problem exists, are meals consisting of multiple components.
In the screenshots the meal consists of a meat burger together with vegetarian fries and sauce.

Instead of just "Essenspräferenzen" we could have "Präferenzen" and "Diäten", allowing to select disliked labels (i.e. disliking all meat options). This way meals which contain both meat and vegetarian will be labeled with the exclamation mark symbol, just as @BuildmodeOne suggested.
