### ISSUE TITLE
Improve error message when backend is down

### ISSUE THREAD

**Issue by alexhorn** [neuland-ingolstadt/neuland.app#280]
Instead of "Bei der Verbindung zum Server ist ein Fehler aufgetreten." we should show a different message that suggests that the user is not at fault to improve user experience. (@Kaazyra)

**Comment by BuildmodeOne** [comment]
As Primuss is currently undergoing maintenance, it would be especially useful to have some information about this as well.
![image](https://github.com/neuland-ingolstadt/neuland.app/assets/39560569/f29fe3a6-99df-4925-a4a8-22d89e5fd9aa)
![image](https://github.com/neuland-ingolstadt/neuland.app/assets/39560569/2dd6ded7-faaf-49c1-bfeb-273a478cfdee)

Here we should also provide the user with a somewhat clearer message instead of a technical error message, especially since Primuss maintenance work is communicated quite clearly.

**Comment by savitakatwe** [comment]
I can Do this changes and send PR @BuildmodeOne
